### ISSUE TITLE
书P107页即第三章SimpleAsncTask在MainActivity使用的问题

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [bboyfeiyu/android_jtm_sourcecode#1]
protected void async()中的 new SimpleAsyncTask<Stirng>()的String,红体说Cannot resolve symbol 'Stirng

 @Override
                protected String doInBackground() 的String ，问题：'doInBackground()' in 'Anonymous class derived from com.example.example_thread_runnable.SimpleAsyncTask' clashes with 'doInBackground()' in 'com.example.example_thread_runnable.SimpleAsyncTask'; attempting to use incompatible return type

 @Override
                protected void onPostExecute(String result)
                {
                    makeToast("onPostExecute : "+ result);
                }

这里是@Override有下划线，还有onPostExecute显示never used

我看了您的源码，但问题仍然存在，请帮助我解决如上问题，万分感激。

**Comment by hehonghui** [comment]
自己看看错误提示
